### PR TITLE
(WIP) Add support for Win32 dlls/libs

### PR DESCRIPTION
**Pull request by shukenmg**
This PR aims to enable packaging to Win32 targets with the x32 bit version of the sdk.

### CODE REVIEW

**Comment by ryanjon2040** [comment]
Hi @shukenmg Thank you for the PR but unfortunately I have no plans to add Win32 support. Unreal Engine 5 officially removed support for Win32 and there is no point in adding deprecated platform.

Screenshot_1

**Comment by shukenmg** [comment]
> Hi @shukenmg Thank you for the PR but unfortunately I have no plans to add Win32 support. Unreal Engine 5 officially removed support for Win32 and there is no point in adding deprecated platform.
> 
> Screenshot_1

Oh, all right, I'll link my branch here when it's done for others who don't use UE5.

**Comment by shukenmg** [comment]
https://github.com/shukenmg/Discord-UE4/tree/win32

Win32 support.
If anyone uses it (rare as that may be) please let me know if there are any issues.

**Comment by ryanjon2040** [comment]
@shukenmg I've updated the Readme to include link to your repo for Win32

**Comment by FlorianFreudiger** [comment]
> Unreal Engine 5 officially removed support for Win32 and there is no point in adding deprecated platform.

Actually Win32 [was already deprecated since UE4.25](https://docs.unrealengine.com/4.26/en-US/WhatsNew/Builds/ReleaseNotes/4_25) (see "Major Upgrade Notes") and since [graphic drivers already dropped Win32](https://nvidia.custhelp.com/app/answers/detail/a_id/4604) and [Microsoft phasing out 32-bit builds](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#section-30---minimum-hardware-requirements-for-windows10-for-desktop-editions) I also don't see a point supporting Win32.

**Comment by shukenmg** [comment]
> > Unreal Engine 5 officially removed support for Win32 and there is no point in adding deprecated platform.
> 
> Actually Win32 [was already deprecated since UE4.25](https://docs.unrealengine.com/4.26/en-US/WhatsNew/Builds/ReleaseNotes/4_25) (see "Major Upgrade Notes") and since [graphic drivers already dropped Win32](https://nvidia.custhelp.com/app/answers/detail/a_id/4604) and [Microsoft phasing out 32-bit builds](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#section-30---minimum-hardware-requirements-for-windows10-for-desktop-editions) I also don't see a point supporting Win32.

I agree, it's kinda like the situation with IE for web design. 
No Dev wants to add support to it, but some users and companies refuse to update.
It's ridiculous.

**Pull request closed without merging**
